### PR TITLE
Mouse wheel events 

### PR DESCRIPTION
**Pull request by azurda**

### CODE REVIEW

**Review by Karjala22 — COMMENTED** [review]
Looks good

**Comment by Karjala22** [comment]
Fixed

**Comment by azurda** [comment]
I guess this is better re-done because of the changes in .DFM

**Comment by azurda** [comment]
nvm this was merged already? https://github.com/df21-net/editor/commit/c071d4d0eb2ffbf4f36f68ba2e02193f2b287ff6

**Pull request closed without merging**
